/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetOrganizationWorkspaces } from "../../funcs/adminGetOrganizationWorkspaces.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrganizationWorkspacesRequest$inboundSchema,
};

export const tool$adminGetOrganizationWorkspaces: ToolDefinition<typeof args> =
  {
    name: "admin-get-organization-workspaces",
    description: `Get all workspaces for a particular organization by ID

Get all workspaces for a particular organization by ID`,
    scopes: ["read"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await adminGetOrganizationWorkspaces(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
