/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetAddOns } from "../../funcs/adminGetAddOns.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAddOnsRequest$inboundSchema,
};

export const tool$adminGetAddOns: ToolDefinition<typeof args> = {
  name: "admin_get-add-ons",
  description:
    `Returns a paginated list of all active billing add ons across all organizations.

Returns a paginated list of all active billing add ons across all organizations.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminGetAddOns(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
