/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetUserWorkspaces } from "../../funcs/adminGetUserWorkspaces.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetUserWorkspacesRequest$inboundSchema,
};

export const tool$adminGetUserWorkspaces: ToolDefinition<typeof args> = {
  name: "admin_get-user-workspaces",
  description: `Returns all workspaces for a particular user by user ID.

Returns all workspaces for a particular user by user ID.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminGetUserWorkspaces(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
