/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetWorkspaceUsers } from "../../funcs/adminGetWorkspaceUsers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWorkspaceUsersRequest$inboundSchema,
};

export const tool$adminGetWorkspaceUsers: ToolDefinition<typeof args> = {
  name: "admin_get-workspace-users",
  description: `Returns all users for a particular workspace by workspace ID.

Returns all users for a particular workspace by workspace ID.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminGetWorkspaceUsers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
