/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetOrganizations } from "../../funcs/adminGetOrganizations.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrganizationsRequest$inboundSchema,
};

export const tool$adminGetOrganizations: ToolDefinition<typeof args> = {
  name: "admin-get-organizations",
  description: `Returns a paginated list of all speakeasy organizations.

Returns a paginated list of all speakeasy organizations.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminGetOrganizations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
