/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetOrganizationAddOns } from "../../funcs/adminGetOrganizationAddOns.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrganizationAddOnsRequest$inboundSchema,
};

export const tool$adminGetOrganizationAddOns: ToolDefinition<typeof args> = {
  name: "admin-get-organization-add-ons",
  description: `Get add ons for a particular organization by ID.

Returns add ons for a particular organization by ID.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminGetOrganizationAddOns(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
