/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetOrganizationBillingLimits } from "../../funcs/adminGetOrganizationBillingLimits.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrganizationBillingLimitsRequest$inboundSchema,
};

export const tool$adminGetOrganizationBillingLimits: ToolDefinition<
  typeof args
> = {
  name: "admin_get-organization-billing-limits",
  description: `Get billing limits for a particular organization by ID.

Gets billing limits for a particular organization by ID.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminGetOrganizationBillingLimits(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
