// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetV1AdminWorkspaces(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "getWorkspaces[0]":
			dir.HandlerFunc("getWorkspaces", testGetWorkspacesGetWorkspaces0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetWorkspacesGetWorkspaces0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "x-api-key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := []components.Workspace{
		components.Workspace{
			CreatedAt:      types.MustTimeFromString("2023-05-02T12:00:20.021Z"),
			ID:             "<id>",
			Name:           "<value>",
			OrganizationID: "<id>",
			Slug:           "<value>",
			UpdatedAt:      types.MustTimeFromString("2025-02-18T09:26:30.719Z"),
			Verified:       false,
		},
		components.Workspace{
			CreatedAt:      types.MustTimeFromString("2024-09-24T01:26:57.125Z"),
			ID:             "<id>",
			Name:           "<value>",
			OrganizationID: "<id>",
			Slug:           "<value>",
			UpdatedAt:      types.MustTimeFromString("2024-05-07T16:49:06.396Z"),
			Verified:       false,
		},
		components.Workspace{
			CreatedAt:      types.MustTimeFromString("2023-02-25T19:21:45.571Z"),
			ID:             "<id>",
			Name:           "<value>",
			OrganizationID: "<id>",
			Slug:           "<value>",
			UpdatedAt:      types.MustTimeFromString("2025-06-02T17:47:10.315Z"),
			Verified:       false,
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
