// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetV1AdminUsers(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "getUsers[0]":
			dir.HandlerFunc("getUsers", testGetUsersGetUsers0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetUsersGetUsers0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "x-api-key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := []components.User{
		components.User{
			ID:            "<id>",
			Email:         "Solon.Botsford28@yahoo.com",
			EmailVerified: false,
			DisplayName:   "Paula.Trantow-Wisozk",
			Confirmed:     true,
			Whitelisted:   false,
			Admin:         false,
			CreatedAt:     types.MustTimeFromString("2025-12-31T21:46:36.485Z"),
			UpdatedAt:     types.MustTimeFromString("2023-11-20T11:07:55.022Z"),
		},
		components.User{
			ID:            "<id>",
			Email:         "Dante.Koch82@yahoo.com",
			EmailVerified: true,
			DisplayName:   "Dillan.Crona31",
			Confirmed:     false,
			Whitelisted:   true,
			Admin:         true,
			CreatedAt:     types.MustTimeFromString("2025-04-28T03:13:22.190Z"),
			UpdatedAt:     types.MustTimeFromString("2023-04-29T04:53:38.500Z"),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
