/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SpeakeasyAdminCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$adminGetAddOns } from "./tools/adminGetAddOns.js";
import { tool$adminGetOrganization } from "./tools/adminGetOrganization.js";
import { tool$adminGetOrganizationAddOns } from "./tools/adminGetOrganizationAddOns.js";
import { tool$adminGetOrganizationBillingLimits } from "./tools/adminGetOrganizationBillingLimits.js";
import { tool$adminGetOrganizations } from "./tools/adminGetOrganizations.js";
import { tool$adminGetOrganizationUsage } from "./tools/adminGetOrganizationUsage.js";
import { tool$adminGetOrganizationWorkspaces } from "./tools/adminGetOrganizationWorkspaces.js";
import { tool$adminGetUser } from "./tools/adminGetUser.js";
import { tool$adminGetUsers } from "./tools/adminGetUsers.js";
import { tool$adminGetUserWorkspaces } from "./tools/adminGetUserWorkspaces.js";
import { tool$adminGetWorkspace } from "./tools/adminGetWorkspace.js";
import { tool$adminGetWorkspaces } from "./tools/adminGetWorkspaces.js";
import { tool$adminGetWorkspaceUsers } from "./tools/adminGetWorkspaceUsers.js";
import { tool$adminSearchEvents } from "./tools/adminSearchEvents.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apiKey?: SDKOptions["apiKey"] | undefined;
  server?: SDKOptions["server"] | undefined;
}) {
  const server = new McpServer({
    name: "SpeakeasyAdmin",
    version: "0.3.1",
  });

  const client = new SpeakeasyAdminCore({
    apiKey: deps.apiKey,
    serverURL: deps.serverURL,
    server: deps.server,
  });

  const scopes = new Set(deps.scopes ?? mcpScopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const register = { tool, resource, resourceTemplate };
  void register; // suppress unused warnings

  tool(tool$adminGetOrganizations);
  tool(tool$adminGetOrganization);
  tool(tool$adminGetOrganizationWorkspaces);
  tool(tool$adminGetOrganizationBillingLimits);
  tool(tool$adminGetOrganizationUsage);
  tool(tool$adminGetAddOns);
  tool(tool$adminGetOrganizationAddOns);
  tool(tool$adminGetUsers);
  tool(tool$adminGetUserWorkspaces);
  tool(tool$adminGetUser);
  tool(tool$adminGetWorkspaces);
  tool(tool$adminGetWorkspaceUsers);
  tool(tool$adminGetWorkspace);
  tool(tool$adminSearchEvents);

  return server;
}
