// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAddOnsRequest struct {
	// The maximum number of organizations to return.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The number of organizations to skip before starting to return results.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *GetAddOnsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetAddOnsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type GetAddOnsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	OrganizationBillingAddOns []components.OrganizationBillingAddOn
}

func (o *GetAddOnsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAddOnsResponse) GetOrganizationBillingAddOns() []components.OrganizationBillingAddOn {
	if o == nil {
		return nil
	}
	return o.OrganizationBillingAddOns
}
