// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOrganizationsRequest struct {
	// The maximum number of organizations to return.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The number of organizations to skip before starting to return results.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *GetOrganizationsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetOrganizationsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type GetOrganizationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Organizations []components.Organization
}

func (o *GetOrganizationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOrganizationsResponse) GetOrganizations() []components.Organization {
	if o == nil {
		return nil
	}
	return o.Organizations
}
