// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOrganizationUsageRequest struct {
	// Unique identifier of the organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationID"`
}

func (o *GetOrganizationUsageRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

type GetOrganizationUsageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	OrganizationUsageResponse *components.OrganizationUsageResponse
}

func (o *GetOrganizationUsageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOrganizationUsageResponse) GetOrganizationUsageResponse() *components.OrganizationUsageResponse {
	if o == nil {
		return nil
	}
	return o.OrganizationUsageResponse
}
