// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOrganizationRequest struct {
	// Unique identifier of the organization.
	OrganizationID *string `queryParam:"style=form,explode=true,name=organization_id"`
	// URL-friendly identifier of the organization.
	OrganizationSlug *string `queryParam:"style=form,explode=true,name=organization_slug"`
}

func (o *GetOrganizationRequest) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *GetOrganizationRequest) GetOrganizationSlug() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationSlug
}

type GetOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Organization *components.Organization
}

func (o *GetOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOrganizationResponse) GetOrganization() *components.Organization {
	if o == nil {
		return nil
	}
	return o.Organization
}
