// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOrganizationWorkspacesRequest struct {
	// Unique identifier of the organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationID"`
}

func (o *GetOrganizationWorkspacesRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

type GetOrganizationWorkspacesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Workspaces []components.Workspace
}

func (o *GetOrganizationWorkspacesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOrganizationWorkspacesResponse) GetWorkspaces() []components.Workspace {
	if o == nil {
		return nil
	}
	return o.Workspaces
}
