// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOrganizationBillingLimitsRequest struct {
	// Unique identifier of the organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationID"`
}

func (o *GetOrganizationBillingLimitsRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

// GetOrganizationBillingLimitsResponseBody - OK
type GetOrganizationBillingLimitsResponseBody struct {
	BillingLimits []components.BillingLimit `json:"billing_limits"`
}

func (o *GetOrganizationBillingLimitsResponseBody) GetBillingLimits() []components.BillingLimit {
	if o == nil {
		return []components.BillingLimit{}
	}
	return o.BillingLimits
}

type GetOrganizationBillingLimitsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *GetOrganizationBillingLimitsResponseBody
}

func (o *GetOrganizationBillingLimitsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOrganizationBillingLimitsResponse) GetObject() *GetOrganizationBillingLimitsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
