// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOrganizationAddOnsRequest struct {
	// Unique identifier of the organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationID"`
}

func (o *GetOrganizationAddOnsRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

// GetOrganizationAddOnsResponseBody - OK
type GetOrganizationAddOnsResponseBody struct {
	AddOns []components.BillingAddOn `json:"add_ons"`
}

func (o *GetOrganizationAddOnsResponseBody) GetAddOns() []components.BillingAddOn {
	if o == nil {
		return []components.BillingAddOn{}
	}
	return o.AddOns
}

type GetOrganizationAddOnsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *GetOrganizationAddOnsResponseBody
}

func (o *GetOrganizationAddOnsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOrganizationAddOnsResponse) GetObject() *GetOrganizationAddOnsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
