// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetUserRequest struct {
	// Unique identifier of the user.
	UserID *string `queryParam:"style=form,explode=true,name=user_id"`
	// Email address of the user.
	Email *string `queryParam:"style=form,explode=true,name=email"`
}

func (o *GetUserRequest) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *GetUserRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

type GetUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	User *components.User
}

func (o *GetUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUserResponse) GetUser() *components.User {
	if o == nil {
		return nil
	}
	return o.User
}
