// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetUsersRequest struct {
	// The maximum number of organizations to return.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The number of organizations to skip before starting to return results.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *GetUsersRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetUsersRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type GetUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Users []components.User
}

func (o *GetUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUsersResponse) GetUsers() []components.User {
	if o == nil {
		return nil
	}
	return o.Users
}
