// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetWorkspaceRequest struct {
	// Unique identifier of the workspace.
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

func (o *GetWorkspaceRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

type GetWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Workspace *components.Workspace
}

func (o *GetWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWorkspaceResponse) GetWorkspace() *components.Workspace {
	if o == nil {
		return nil
	}
	return o.Workspace
}
