// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetWorkspaceRequest struct {
	// Unique identifier of the workspace.
	WorkspaceID *string `queryParam:"style=form,explode=true,name=workspace_id"`
	// URL-friendly identifier of the organization.
	OrganizationSlug *string `queryParam:"style=form,explode=true,name=organization_slug"`
	// URL-friendly identifier of the workspace.
	WorkspaceSlug *string `queryParam:"style=form,explode=true,name=workspace_slug"`
}

func (o *GetWorkspaceRequest) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *GetWorkspaceRequest) GetOrganizationSlug() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationSlug
}

func (o *GetWorkspaceRequest) GetWorkspaceSlug() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceSlug
}

type GetWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Workspace *components.Workspace
}

func (o *GetWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWorkspaceResponse) GetWorkspace() *components.Workspace {
	if o == nil {
		return nil
	}
	return o.Workspace
}
