// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetWorkspaceUsersRequest struct {
	// Unique identifier of the workspace.
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

func (o *GetWorkspaceUsersRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

type GetWorkspaceUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Users []components.User
}

func (o *GetWorkspaceUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWorkspaceUsersResponse) GetUsers() []components.User {
	if o == nil {
		return nil
	}
	return o.Users
}
