/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrganizationWorkspacesRequest = {
  /**
   * Unique identifier of the organization.
   */
  organizationID: string;
};

/** @internal */
export const GetOrganizationWorkspacesRequest$inboundSchema: z.ZodType<
  GetOrganizationWorkspacesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationID: z.string(),
});

/** @internal */
export type GetOrganizationWorkspacesRequest$Outbound = {
  organizationID: string;
};

/** @internal */
export const GetOrganizationWorkspacesRequest$outboundSchema: z.ZodType<
  GetOrganizationWorkspacesRequest$Outbound,
  z.ZodTypeDef,
  GetOrganizationWorkspacesRequest
> = z.object({
  organizationID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrganizationWorkspacesRequest$ {
  /** @deprecated use `GetOrganizationWorkspacesRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrganizationWorkspacesRequest$inboundSchema;
  /** @deprecated use `GetOrganizationWorkspacesRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrganizationWorkspacesRequest$outboundSchema;
  /** @deprecated use `GetOrganizationWorkspacesRequest$Outbound` instead. */
  export type Outbound = GetOrganizationWorkspacesRequest$Outbound;
}

export function getOrganizationWorkspacesRequestToJSON(
  getOrganizationWorkspacesRequest: GetOrganizationWorkspacesRequest,
): string {
  return JSON.stringify(
    GetOrganizationWorkspacesRequest$outboundSchema.parse(
      getOrganizationWorkspacesRequest,
    ),
  );
}

export function getOrganizationWorkspacesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationWorkspacesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationWorkspacesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationWorkspacesRequest' from JSON`,
  );
}
