/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUsersRequest = {
  /**
   * The maximum number of organizations to return.
   */
  limit?: number | undefined;
  /**
   * The number of organizations to skip before starting to return results.
   */
  offset?: number | undefined;
};

/** @internal */
export const GetUsersRequest$inboundSchema: z.ZodType<
  GetUsersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
});

/** @internal */
export type GetUsersRequest$Outbound = {
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const GetUsersRequest$outboundSchema: z.ZodType<
  GetUsersRequest$Outbound,
  z.ZodTypeDef,
  GetUsersRequest
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUsersRequest$ {
  /** @deprecated use `GetUsersRequest$inboundSchema` instead. */
  export const inboundSchema = GetUsersRequest$inboundSchema;
  /** @deprecated use `GetUsersRequest$outboundSchema` instead. */
  export const outboundSchema = GetUsersRequest$outboundSchema;
  /** @deprecated use `GetUsersRequest$Outbound` instead. */
  export type Outbound = GetUsersRequest$Outbound;
}

export function getUsersRequestToJSON(
  getUsersRequest: GetUsersRequest,
): string {
  return JSON.stringify(GetUsersRequest$outboundSchema.parse(getUsersRequest));
}

export function getUsersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUsersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsersRequest' from JSON`,
  );
}
