// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CliEvent struct {
	ContinuousIntegrationEnvironment *string         `json:"continuous_integration_environment,omitempty"`
	CreatedAt                        string          `json:"created_at"`
	ExecutionID                      string          `json:"execution_id"`
	GenerateRepoURL                  *string         `json:"generate_repo_url,omitempty"`
	GenerateTarget                   *string         `json:"generate_target,omitempty"`
	GenerateTargetName               *string         `json:"generate_target_name,omitempty"`
	GhActionOrganization             *string         `json:"gh_action_organization,omitempty"`
	GhActionRunLink                  *string         `json:"gh_action_run_link,omitempty"`
	InteractionType                  InteractionType `json:"interaction_type"`
	LintReportErrorCount             *int64          `json:"lint_report_error_count,omitempty"`
	LintReportInfoCount              *int64          `json:"lint_report_info_count,omitempty"`
	LintReportWarningCount           *int64          `json:"lint_report_warning_count,omitempty"`
	SpeakeasyVersion                 string          `json:"speakeasy_version"`
	Success                          bool            `json:"success"`
	WorkspaceID                      string          `json:"workspace_id"`
}

func (o *CliEvent) GetContinuousIntegrationEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.ContinuousIntegrationEnvironment
}

func (o *CliEvent) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *CliEvent) GetExecutionID() string {
	if o == nil {
		return ""
	}
	return o.ExecutionID
}

func (o *CliEvent) GetGenerateRepoURL() *string {
	if o == nil {
		return nil
	}
	return o.GenerateRepoURL
}

func (o *CliEvent) GetGenerateTarget() *string {
	if o == nil {
		return nil
	}
	return o.GenerateTarget
}

func (o *CliEvent) GetGenerateTargetName() *string {
	if o == nil {
		return nil
	}
	return o.GenerateTargetName
}

func (o *CliEvent) GetGhActionOrganization() *string {
	if o == nil {
		return nil
	}
	return o.GhActionOrganization
}

func (o *CliEvent) GetGhActionRunLink() *string {
	if o == nil {
		return nil
	}
	return o.GhActionRunLink
}

func (o *CliEvent) GetInteractionType() InteractionType {
	if o == nil {
		return InteractionType("")
	}
	return o.InteractionType
}

func (o *CliEvent) GetLintReportErrorCount() *int64 {
	if o == nil {
		return nil
	}
	return o.LintReportErrorCount
}

func (o *CliEvent) GetLintReportInfoCount() *int64 {
	if o == nil {
		return nil
	}
	return o.LintReportInfoCount
}

func (o *CliEvent) GetLintReportWarningCount() *int64 {
	if o == nil {
		return nil
	}
	return o.LintReportWarningCount
}

func (o *CliEvent) GetSpeakeasyVersion() string {
	if o == nil {
		return ""
	}
	return o.SpeakeasyVersion
}

func (o *CliEvent) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

func (o *CliEvent) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
