// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type OrganizationBillingAddOn struct {
	// The unique identifier for the organization.
	OrganizationID string       `json:"organization_id"`
	AddOn          BillingAddOn `json:"add_on"`
	// The timestamp when the add-on was created.
	CreatedAt time.Time `json:"created_at"`
}

func (o OrganizationBillingAddOn) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationBillingAddOn) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationBillingAddOn) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationBillingAddOn) GetAddOn() BillingAddOn {
	if o == nil {
		return BillingAddOn("")
	}
	return o.AddOn
}

func (o *OrganizationBillingAddOn) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}
