/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationUsage,
  OrganizationUsage$inboundSchema,
  OrganizationUsage$Outbound,
  OrganizationUsage$outboundSchema,
} from "./organizationusage.js";

/**
 * A billing summary of organization usage
 */
export type OrganizationUsageResponse = {
  usage: Array<OrganizationUsage>;
  /**
   * Expiry date of the free trial, will be null if no trial
   */
  freeTrialExpiry?: Date | undefined;
  /**
   * Total number of allowed languages, -1 if unlimited
   */
  totalAllowedLanguages: number;
  /**
   * List of allowed languages
   */
  allowedLanguages: Array<string>;
};

/** @internal */
export const OrganizationUsageResponse$inboundSchema: z.ZodType<
  OrganizationUsageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  usage: z.array(OrganizationUsage$inboundSchema),
  free_trial_expiry: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  total_allowed_languages: z.number().int(),
  allowed_languages: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "free_trial_expiry": "freeTrialExpiry",
    "total_allowed_languages": "totalAllowedLanguages",
    "allowed_languages": "allowedLanguages",
  });
});

/** @internal */
export type OrganizationUsageResponse$Outbound = {
  usage: Array<OrganizationUsage$Outbound>;
  free_trial_expiry?: string | undefined;
  total_allowed_languages: number;
  allowed_languages: Array<string>;
};

/** @internal */
export const OrganizationUsageResponse$outboundSchema: z.ZodType<
  OrganizationUsageResponse$Outbound,
  z.ZodTypeDef,
  OrganizationUsageResponse
> = z.object({
  usage: z.array(OrganizationUsage$outboundSchema),
  freeTrialExpiry: z.date().transform(v => v.toISOString()).optional(),
  totalAllowedLanguages: z.number().int(),
  allowedLanguages: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    freeTrialExpiry: "free_trial_expiry",
    totalAllowedLanguages: "total_allowed_languages",
    allowedLanguages: "allowed_languages",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationUsageResponse$ {
  /** @deprecated use `OrganizationUsageResponse$inboundSchema` instead. */
  export const inboundSchema = OrganizationUsageResponse$inboundSchema;
  /** @deprecated use `OrganizationUsageResponse$outboundSchema` instead. */
  export const outboundSchema = OrganizationUsageResponse$outboundSchema;
  /** @deprecated use `OrganizationUsageResponse$Outbound` instead. */
  export type Outbound = OrganizationUsageResponse$Outbound;
}

export function organizationUsageResponseToJSON(
  organizationUsageResponse: OrganizationUsageResponse,
): string {
  return JSON.stringify(
    OrganizationUsageResponse$outboundSchema.parse(organizationUsageResponse),
  );
}

export function organizationUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationUsageResponse' from JSON`,
  );
}
